# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/anmolsoni/Nextcloud/projects/RegionalDSKSFC

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/anmolsoni/Nextcloud/projects/RegionalDSKSFC

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/anmolsoni/Nextcloud/projects/RegionalDSKSFC/CMakeFiles /Users/anmolsoni/Nextcloud/projects/RegionalDSKSFC//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/anmolsoni/Nextcloud/projects/RegionalDSKSFC/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dsk_SFC

# Build rule for target.
dsk_SFC: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dsk_SFC
.PHONY : dsk_SFC

# fast build rule for target.
dsk_SFC/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/build
.PHONY : dsk_SFC/fast

auxiliary/betadev.o: auxiliary/betadev.cpp.o
.PHONY : auxiliary/betadev.o

# target to build an object file
auxiliary/betadev.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/auxiliary/betadev.cpp.o
.PHONY : auxiliary/betadev.cpp.o

auxiliary/betadev.i: auxiliary/betadev.cpp.i
.PHONY : auxiliary/betadev.i

# target to preprocess a source file
auxiliary/betadev.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/auxiliary/betadev.cpp.i
.PHONY : auxiliary/betadev.cpp.i

auxiliary/betadev.s: auxiliary/betadev.cpp.s
.PHONY : auxiliary/betadev.s

# target to generate assembly for a file
auxiliary/betadev.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/auxiliary/betadev.cpp.s
.PHONY : auxiliary/betadev.cpp.s

auxiliary/bnldev.o: auxiliary/bnldev.cpp.o
.PHONY : auxiliary/bnldev.o

# target to build an object file
auxiliary/bnldev.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/auxiliary/bnldev.cpp.o
.PHONY : auxiliary/bnldev.cpp.o

auxiliary/bnldev.i: auxiliary/bnldev.cpp.i
.PHONY : auxiliary/bnldev.i

# target to preprocess a source file
auxiliary/bnldev.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/auxiliary/bnldev.cpp.i
.PHONY : auxiliary/bnldev.cpp.i

auxiliary/bnldev.s: auxiliary/bnldev.cpp.s
.PHONY : auxiliary/bnldev.s

# target to generate assembly for a file
auxiliary/bnldev.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/auxiliary/bnldev.cpp.s
.PHONY : auxiliary/bnldev.cpp.s

auxiliary/gammln.o: auxiliary/gammln.cpp.o
.PHONY : auxiliary/gammln.o

# target to build an object file
auxiliary/gammln.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/auxiliary/gammln.cpp.o
.PHONY : auxiliary/gammln.cpp.o

auxiliary/gammln.i: auxiliary/gammln.cpp.i
.PHONY : auxiliary/gammln.i

# target to preprocess a source file
auxiliary/gammln.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/auxiliary/gammln.cpp.i
.PHONY : auxiliary/gammln.cpp.i

auxiliary/gammln.s: auxiliary/gammln.cpp.s
.PHONY : auxiliary/gammln.s

# target to generate assembly for a file
auxiliary/gammln.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/auxiliary/gammln.cpp.s
.PHONY : auxiliary/gammln.cpp.s

auxiliary/gasdev.o: auxiliary/gasdev.cpp.o
.PHONY : auxiliary/gasdev.o

# target to build an object file
auxiliary/gasdev.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/auxiliary/gasdev.cpp.o
.PHONY : auxiliary/gasdev.cpp.o

auxiliary/gasdev.i: auxiliary/gasdev.cpp.i
.PHONY : auxiliary/gasdev.i

# target to preprocess a source file
auxiliary/gasdev.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/auxiliary/gasdev.cpp.i
.PHONY : auxiliary/gasdev.cpp.i

auxiliary/gasdev.s: auxiliary/gasdev.cpp.s
.PHONY : auxiliary/gasdev.s

# target to generate assembly for a file
auxiliary/gasdev.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/auxiliary/gasdev.cpp.s
.PHONY : auxiliary/gasdev.cpp.s

auxiliary/ran1.o: auxiliary/ran1.cpp.o
.PHONY : auxiliary/ran1.o

# target to build an object file
auxiliary/ran1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/auxiliary/ran1.cpp.o
.PHONY : auxiliary/ran1.cpp.o

auxiliary/ran1.i: auxiliary/ran1.cpp.i
.PHONY : auxiliary/ran1.i

# target to preprocess a source file
auxiliary/ran1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/auxiliary/ran1.cpp.i
.PHONY : auxiliary/ran1.cpp.i

auxiliary/ran1.s: auxiliary/ran1.cpp.s
.PHONY : auxiliary/ran1.s

# target to generate assembly for a file
auxiliary/ran1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/auxiliary/ran1.cpp.s
.PHONY : auxiliary/ran1.cpp.s

dsk_sfc_main.o: dsk_sfc_main.cpp.o
.PHONY : dsk_sfc_main.o

# target to build an object file
dsk_sfc_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/dsk_sfc_main.cpp.o
.PHONY : dsk_sfc_main.cpp.o

dsk_sfc_main.i: dsk_sfc_main.cpp.i
.PHONY : dsk_sfc_main.i

# target to preprocess a source file
dsk_sfc_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/dsk_sfc_main.cpp.i
.PHONY : dsk_sfc_main.cpp.i

dsk_sfc_main.s: dsk_sfc_main.cpp.s
.PHONY : dsk_sfc_main.s

# target to generate assembly for a file
dsk_sfc_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/dsk_sfc_main.cpp.s
.PHONY : dsk_sfc_main.cpp.s

modules/module_climate_sfc.o: modules/module_climate_sfc.cpp.o
.PHONY : modules/module_climate_sfc.o

# target to build an object file
modules/module_climate_sfc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/modules/module_climate_sfc.cpp.o
.PHONY : modules/module_climate_sfc.cpp.o

modules/module_climate_sfc.i: modules/module_climate_sfc.cpp.i
.PHONY : modules/module_climate_sfc.i

# target to preprocess a source file
modules/module_climate_sfc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/modules/module_climate_sfc.cpp.i
.PHONY : modules/module_climate_sfc.cpp.i

modules/module_climate_sfc.s: modules/module_climate_sfc.cpp.s
.PHONY : modules/module_climate_sfc.s

# target to generate assembly for a file
modules/module_climate_sfc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/modules/module_climate_sfc.cpp.s
.PHONY : modules/module_climate_sfc.cpp.s

modules/module_energy_sfc.o: modules/module_energy_sfc.cpp.o
.PHONY : modules/module_energy_sfc.o

# target to build an object file
modules/module_energy_sfc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/modules/module_energy_sfc.cpp.o
.PHONY : modules/module_energy_sfc.cpp.o

modules/module_energy_sfc.i: modules/module_energy_sfc.cpp.i
.PHONY : modules/module_energy_sfc.i

# target to preprocess a source file
modules/module_energy_sfc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/modules/module_energy_sfc.cpp.i
.PHONY : modules/module_energy_sfc.cpp.i

modules/module_energy_sfc.s: modules/module_energy_sfc.cpp.s
.PHONY : modules/module_energy_sfc.s

# target to generate assembly for a file
modules/module_energy_sfc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/modules/module_energy_sfc.cpp.s
.PHONY : modules/module_energy_sfc.cpp.s

modules/module_finance_sfc.o: modules/module_finance_sfc.cpp.o
.PHONY : modules/module_finance_sfc.o

# target to build an object file
modules/module_finance_sfc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/modules/module_finance_sfc.cpp.o
.PHONY : modules/module_finance_sfc.cpp.o

modules/module_finance_sfc.i: modules/module_finance_sfc.cpp.i
.PHONY : modules/module_finance_sfc.i

# target to preprocess a source file
modules/module_finance_sfc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/modules/module_finance_sfc.cpp.i
.PHONY : modules/module_finance_sfc.cpp.i

modules/module_finance_sfc.s: modules/module_finance_sfc.cpp.s
.PHONY : modules/module_finance_sfc.s

# target to generate assembly for a file
modules/module_finance_sfc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/modules/module_finance_sfc.cpp.s
.PHONY : modules/module_finance_sfc.cpp.s

modules/module_macro_sfc.o: modules/module_macro_sfc.cpp.o
.PHONY : modules/module_macro_sfc.o

# target to build an object file
modules/module_macro_sfc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/modules/module_macro_sfc.cpp.o
.PHONY : modules/module_macro_sfc.cpp.o

modules/module_macro_sfc.i: modules/module_macro_sfc.cpp.i
.PHONY : modules/module_macro_sfc.i

# target to preprocess a source file
modules/module_macro_sfc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/modules/module_macro_sfc.cpp.i
.PHONY : modules/module_macro_sfc.cpp.i

modules/module_macro_sfc.s: modules/module_macro_sfc.cpp.s
.PHONY : modules/module_macro_sfc.s

# target to generate assembly for a file
modules/module_macro_sfc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/modules/module_macro_sfc.cpp.s
.PHONY : modules/module_macro_sfc.cpp.s

newmat10/bandmat.o: newmat10/bandmat.cpp.o
.PHONY : newmat10/bandmat.o

# target to build an object file
newmat10/bandmat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/bandmat.cpp.o
.PHONY : newmat10/bandmat.cpp.o

newmat10/bandmat.i: newmat10/bandmat.cpp.i
.PHONY : newmat10/bandmat.i

# target to preprocess a source file
newmat10/bandmat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/bandmat.cpp.i
.PHONY : newmat10/bandmat.cpp.i

newmat10/bandmat.s: newmat10/bandmat.cpp.s
.PHONY : newmat10/bandmat.s

# target to generate assembly for a file
newmat10/bandmat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/bandmat.cpp.s
.PHONY : newmat10/bandmat.cpp.s

newmat10/cholesky.o: newmat10/cholesky.cpp.o
.PHONY : newmat10/cholesky.o

# target to build an object file
newmat10/cholesky.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/cholesky.cpp.o
.PHONY : newmat10/cholesky.cpp.o

newmat10/cholesky.i: newmat10/cholesky.cpp.i
.PHONY : newmat10/cholesky.i

# target to preprocess a source file
newmat10/cholesky.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/cholesky.cpp.i
.PHONY : newmat10/cholesky.cpp.i

newmat10/cholesky.s: newmat10/cholesky.cpp.s
.PHONY : newmat10/cholesky.s

# target to generate assembly for a file
newmat10/cholesky.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/cholesky.cpp.s
.PHONY : newmat10/cholesky.cpp.s

newmat10/evalue.o: newmat10/evalue.cpp.o
.PHONY : newmat10/evalue.o

# target to build an object file
newmat10/evalue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/evalue.cpp.o
.PHONY : newmat10/evalue.cpp.o

newmat10/evalue.i: newmat10/evalue.cpp.i
.PHONY : newmat10/evalue.i

# target to preprocess a source file
newmat10/evalue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/evalue.cpp.i
.PHONY : newmat10/evalue.cpp.i

newmat10/evalue.s: newmat10/evalue.cpp.s
.PHONY : newmat10/evalue.s

# target to generate assembly for a file
newmat10/evalue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/evalue.cpp.s
.PHONY : newmat10/evalue.cpp.s

newmat10/fft.o: newmat10/fft.cpp.o
.PHONY : newmat10/fft.o

# target to build an object file
newmat10/fft.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/fft.cpp.o
.PHONY : newmat10/fft.cpp.o

newmat10/fft.i: newmat10/fft.cpp.i
.PHONY : newmat10/fft.i

# target to preprocess a source file
newmat10/fft.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/fft.cpp.i
.PHONY : newmat10/fft.cpp.i

newmat10/fft.s: newmat10/fft.cpp.s
.PHONY : newmat10/fft.s

# target to generate assembly for a file
newmat10/fft.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/fft.cpp.s
.PHONY : newmat10/fft.cpp.s

newmat10/hholder.o: newmat10/hholder.cpp.o
.PHONY : newmat10/hholder.o

# target to build an object file
newmat10/hholder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/hholder.cpp.o
.PHONY : newmat10/hholder.cpp.o

newmat10/hholder.i: newmat10/hholder.cpp.i
.PHONY : newmat10/hholder.i

# target to preprocess a source file
newmat10/hholder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/hholder.cpp.i
.PHONY : newmat10/hholder.cpp.i

newmat10/hholder.s: newmat10/hholder.cpp.s
.PHONY : newmat10/hholder.s

# target to generate assembly for a file
newmat10/hholder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/hholder.cpp.s
.PHONY : newmat10/hholder.cpp.s

newmat10/jacobi.o: newmat10/jacobi.cpp.o
.PHONY : newmat10/jacobi.o

# target to build an object file
newmat10/jacobi.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/jacobi.cpp.o
.PHONY : newmat10/jacobi.cpp.o

newmat10/jacobi.i: newmat10/jacobi.cpp.i
.PHONY : newmat10/jacobi.i

# target to preprocess a source file
newmat10/jacobi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/jacobi.cpp.i
.PHONY : newmat10/jacobi.cpp.i

newmat10/jacobi.s: newmat10/jacobi.cpp.s
.PHONY : newmat10/jacobi.s

# target to generate assembly for a file
newmat10/jacobi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/jacobi.cpp.s
.PHONY : newmat10/jacobi.cpp.s

newmat10/myexcept.o: newmat10/myexcept.cpp.o
.PHONY : newmat10/myexcept.o

# target to build an object file
newmat10/myexcept.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/myexcept.cpp.o
.PHONY : newmat10/myexcept.cpp.o

newmat10/myexcept.i: newmat10/myexcept.cpp.i
.PHONY : newmat10/myexcept.i

# target to preprocess a source file
newmat10/myexcept.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/myexcept.cpp.i
.PHONY : newmat10/myexcept.cpp.i

newmat10/myexcept.s: newmat10/myexcept.cpp.s
.PHONY : newmat10/myexcept.s

# target to generate assembly for a file
newmat10/myexcept.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/myexcept.cpp.s
.PHONY : newmat10/myexcept.cpp.s

newmat10/newfft.o: newmat10/newfft.cpp.o
.PHONY : newmat10/newfft.o

# target to build an object file
newmat10/newfft.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newfft.cpp.o
.PHONY : newmat10/newfft.cpp.o

newmat10/newfft.i: newmat10/newfft.cpp.i
.PHONY : newmat10/newfft.i

# target to preprocess a source file
newmat10/newfft.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newfft.cpp.i
.PHONY : newmat10/newfft.cpp.i

newmat10/newfft.s: newmat10/newfft.cpp.s
.PHONY : newmat10/newfft.s

# target to generate assembly for a file
newmat10/newfft.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newfft.cpp.s
.PHONY : newmat10/newfft.cpp.s

newmat10/newmat1.o: newmat10/newmat1.cpp.o
.PHONY : newmat10/newmat1.o

# target to build an object file
newmat10/newmat1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmat1.cpp.o
.PHONY : newmat10/newmat1.cpp.o

newmat10/newmat1.i: newmat10/newmat1.cpp.i
.PHONY : newmat10/newmat1.i

# target to preprocess a source file
newmat10/newmat1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmat1.cpp.i
.PHONY : newmat10/newmat1.cpp.i

newmat10/newmat1.s: newmat10/newmat1.cpp.s
.PHONY : newmat10/newmat1.s

# target to generate assembly for a file
newmat10/newmat1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmat1.cpp.s
.PHONY : newmat10/newmat1.cpp.s

newmat10/newmat2.o: newmat10/newmat2.cpp.o
.PHONY : newmat10/newmat2.o

# target to build an object file
newmat10/newmat2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmat2.cpp.o
.PHONY : newmat10/newmat2.cpp.o

newmat10/newmat2.i: newmat10/newmat2.cpp.i
.PHONY : newmat10/newmat2.i

# target to preprocess a source file
newmat10/newmat2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmat2.cpp.i
.PHONY : newmat10/newmat2.cpp.i

newmat10/newmat2.s: newmat10/newmat2.cpp.s
.PHONY : newmat10/newmat2.s

# target to generate assembly for a file
newmat10/newmat2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmat2.cpp.s
.PHONY : newmat10/newmat2.cpp.s

newmat10/newmat3.o: newmat10/newmat3.cpp.o
.PHONY : newmat10/newmat3.o

# target to build an object file
newmat10/newmat3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmat3.cpp.o
.PHONY : newmat10/newmat3.cpp.o

newmat10/newmat3.i: newmat10/newmat3.cpp.i
.PHONY : newmat10/newmat3.i

# target to preprocess a source file
newmat10/newmat3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmat3.cpp.i
.PHONY : newmat10/newmat3.cpp.i

newmat10/newmat3.s: newmat10/newmat3.cpp.s
.PHONY : newmat10/newmat3.s

# target to generate assembly for a file
newmat10/newmat3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmat3.cpp.s
.PHONY : newmat10/newmat3.cpp.s

newmat10/newmat4.o: newmat10/newmat4.cpp.o
.PHONY : newmat10/newmat4.o

# target to build an object file
newmat10/newmat4.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmat4.cpp.o
.PHONY : newmat10/newmat4.cpp.o

newmat10/newmat4.i: newmat10/newmat4.cpp.i
.PHONY : newmat10/newmat4.i

# target to preprocess a source file
newmat10/newmat4.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmat4.cpp.i
.PHONY : newmat10/newmat4.cpp.i

newmat10/newmat4.s: newmat10/newmat4.cpp.s
.PHONY : newmat10/newmat4.s

# target to generate assembly for a file
newmat10/newmat4.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmat4.cpp.s
.PHONY : newmat10/newmat4.cpp.s

newmat10/newmat5.o: newmat10/newmat5.cpp.o
.PHONY : newmat10/newmat5.o

# target to build an object file
newmat10/newmat5.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmat5.cpp.o
.PHONY : newmat10/newmat5.cpp.o

newmat10/newmat5.i: newmat10/newmat5.cpp.i
.PHONY : newmat10/newmat5.i

# target to preprocess a source file
newmat10/newmat5.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmat5.cpp.i
.PHONY : newmat10/newmat5.cpp.i

newmat10/newmat5.s: newmat10/newmat5.cpp.s
.PHONY : newmat10/newmat5.s

# target to generate assembly for a file
newmat10/newmat5.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmat5.cpp.s
.PHONY : newmat10/newmat5.cpp.s

newmat10/newmat6.o: newmat10/newmat6.cpp.o
.PHONY : newmat10/newmat6.o

# target to build an object file
newmat10/newmat6.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmat6.cpp.o
.PHONY : newmat10/newmat6.cpp.o

newmat10/newmat6.i: newmat10/newmat6.cpp.i
.PHONY : newmat10/newmat6.i

# target to preprocess a source file
newmat10/newmat6.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmat6.cpp.i
.PHONY : newmat10/newmat6.cpp.i

newmat10/newmat6.s: newmat10/newmat6.cpp.s
.PHONY : newmat10/newmat6.s

# target to generate assembly for a file
newmat10/newmat6.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmat6.cpp.s
.PHONY : newmat10/newmat6.cpp.s

newmat10/newmat7.o: newmat10/newmat7.cpp.o
.PHONY : newmat10/newmat7.o

# target to build an object file
newmat10/newmat7.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmat7.cpp.o
.PHONY : newmat10/newmat7.cpp.o

newmat10/newmat7.i: newmat10/newmat7.cpp.i
.PHONY : newmat10/newmat7.i

# target to preprocess a source file
newmat10/newmat7.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmat7.cpp.i
.PHONY : newmat10/newmat7.cpp.i

newmat10/newmat7.s: newmat10/newmat7.cpp.s
.PHONY : newmat10/newmat7.s

# target to generate assembly for a file
newmat10/newmat7.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmat7.cpp.s
.PHONY : newmat10/newmat7.cpp.s

newmat10/newmat8.o: newmat10/newmat8.cpp.o
.PHONY : newmat10/newmat8.o

# target to build an object file
newmat10/newmat8.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmat8.cpp.o
.PHONY : newmat10/newmat8.cpp.o

newmat10/newmat8.i: newmat10/newmat8.cpp.i
.PHONY : newmat10/newmat8.i

# target to preprocess a source file
newmat10/newmat8.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmat8.cpp.i
.PHONY : newmat10/newmat8.cpp.i

newmat10/newmat8.s: newmat10/newmat8.cpp.s
.PHONY : newmat10/newmat8.s

# target to generate assembly for a file
newmat10/newmat8.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmat8.cpp.s
.PHONY : newmat10/newmat8.cpp.s

newmat10/newmat9.o: newmat10/newmat9.cpp.o
.PHONY : newmat10/newmat9.o

# target to build an object file
newmat10/newmat9.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmat9.cpp.o
.PHONY : newmat10/newmat9.cpp.o

newmat10/newmat9.i: newmat10/newmat9.cpp.i
.PHONY : newmat10/newmat9.i

# target to preprocess a source file
newmat10/newmat9.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmat9.cpp.i
.PHONY : newmat10/newmat9.cpp.i

newmat10/newmat9.s: newmat10/newmat9.cpp.s
.PHONY : newmat10/newmat9.s

# target to generate assembly for a file
newmat10/newmat9.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmat9.cpp.s
.PHONY : newmat10/newmat9.cpp.s

newmat10/newmatex.o: newmat10/newmatex.cpp.o
.PHONY : newmat10/newmatex.o

# target to build an object file
newmat10/newmatex.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmatex.cpp.o
.PHONY : newmat10/newmatex.cpp.o

newmat10/newmatex.i: newmat10/newmatex.cpp.i
.PHONY : newmat10/newmatex.i

# target to preprocess a source file
newmat10/newmatex.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmatex.cpp.i
.PHONY : newmat10/newmatex.cpp.i

newmat10/newmatex.s: newmat10/newmatex.cpp.s
.PHONY : newmat10/newmatex.s

# target to generate assembly for a file
newmat10/newmatex.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmatex.cpp.s
.PHONY : newmat10/newmatex.cpp.s

newmat10/newmatnl.o: newmat10/newmatnl.cpp.o
.PHONY : newmat10/newmatnl.o

# target to build an object file
newmat10/newmatnl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmatnl.cpp.o
.PHONY : newmat10/newmatnl.cpp.o

newmat10/newmatnl.i: newmat10/newmatnl.cpp.i
.PHONY : newmat10/newmatnl.i

# target to preprocess a source file
newmat10/newmatnl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmatnl.cpp.i
.PHONY : newmat10/newmatnl.cpp.i

newmat10/newmatnl.s: newmat10/newmatnl.cpp.s
.PHONY : newmat10/newmatnl.s

# target to generate assembly for a file
newmat10/newmatnl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmatnl.cpp.s
.PHONY : newmat10/newmatnl.cpp.s

newmat10/newmatrm.o: newmat10/newmatrm.cpp.o
.PHONY : newmat10/newmatrm.o

# target to build an object file
newmat10/newmatrm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmatrm.cpp.o
.PHONY : newmat10/newmatrm.cpp.o

newmat10/newmatrm.i: newmat10/newmatrm.cpp.i
.PHONY : newmat10/newmatrm.i

# target to preprocess a source file
newmat10/newmatrm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmatrm.cpp.i
.PHONY : newmat10/newmatrm.cpp.i

newmat10/newmatrm.s: newmat10/newmatrm.cpp.s
.PHONY : newmat10/newmatrm.s

# target to generate assembly for a file
newmat10/newmatrm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/newmatrm.cpp.s
.PHONY : newmat10/newmatrm.cpp.s

newmat10/solution.o: newmat10/solution.cpp.o
.PHONY : newmat10/solution.o

# target to build an object file
newmat10/solution.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/solution.cpp.o
.PHONY : newmat10/solution.cpp.o

newmat10/solution.i: newmat10/solution.cpp.i
.PHONY : newmat10/solution.i

# target to preprocess a source file
newmat10/solution.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/solution.cpp.i
.PHONY : newmat10/solution.cpp.i

newmat10/solution.s: newmat10/solution.cpp.s
.PHONY : newmat10/solution.s

# target to generate assembly for a file
newmat10/solution.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/solution.cpp.s
.PHONY : newmat10/solution.cpp.s

newmat10/sort.o: newmat10/sort.cpp.o
.PHONY : newmat10/sort.o

# target to build an object file
newmat10/sort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/sort.cpp.o
.PHONY : newmat10/sort.cpp.o

newmat10/sort.i: newmat10/sort.cpp.i
.PHONY : newmat10/sort.i

# target to preprocess a source file
newmat10/sort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/sort.cpp.i
.PHONY : newmat10/sort.cpp.i

newmat10/sort.s: newmat10/sort.cpp.s
.PHONY : newmat10/sort.s

# target to generate assembly for a file
newmat10/sort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/sort.cpp.s
.PHONY : newmat10/sort.cpp.s

newmat10/submat.o: newmat10/submat.cpp.o
.PHONY : newmat10/submat.o

# target to build an object file
newmat10/submat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/submat.cpp.o
.PHONY : newmat10/submat.cpp.o

newmat10/submat.i: newmat10/submat.cpp.i
.PHONY : newmat10/submat.i

# target to preprocess a source file
newmat10/submat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/submat.cpp.i
.PHONY : newmat10/submat.cpp.i

newmat10/submat.s: newmat10/submat.cpp.s
.PHONY : newmat10/submat.s

# target to generate assembly for a file
newmat10/submat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/submat.cpp.s
.PHONY : newmat10/submat.cpp.s

newmat10/svd.o: newmat10/svd.cpp.o
.PHONY : newmat10/svd.o

# target to build an object file
newmat10/svd.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/svd.cpp.o
.PHONY : newmat10/svd.cpp.o

newmat10/svd.i: newmat10/svd.cpp.i
.PHONY : newmat10/svd.i

# target to preprocess a source file
newmat10/svd.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/svd.cpp.i
.PHONY : newmat10/svd.cpp.i

newmat10/svd.s: newmat10/svd.cpp.s
.PHONY : newmat10/svd.s

# target to generate assembly for a file
newmat10/svd.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsk_SFC.dir/build.make CMakeFiles/dsk_SFC.dir/newmat10/svd.cpp.s
.PHONY : newmat10/svd.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... dsk_SFC"
	@echo "... auxiliary/betadev.o"
	@echo "... auxiliary/betadev.i"
	@echo "... auxiliary/betadev.s"
	@echo "... auxiliary/bnldev.o"
	@echo "... auxiliary/bnldev.i"
	@echo "... auxiliary/bnldev.s"
	@echo "... auxiliary/gammln.o"
	@echo "... auxiliary/gammln.i"
	@echo "... auxiliary/gammln.s"
	@echo "... auxiliary/gasdev.o"
	@echo "... auxiliary/gasdev.i"
	@echo "... auxiliary/gasdev.s"
	@echo "... auxiliary/ran1.o"
	@echo "... auxiliary/ran1.i"
	@echo "... auxiliary/ran1.s"
	@echo "... dsk_sfc_main.o"
	@echo "... dsk_sfc_main.i"
	@echo "... dsk_sfc_main.s"
	@echo "... modules/module_climate_sfc.o"
	@echo "... modules/module_climate_sfc.i"
	@echo "... modules/module_climate_sfc.s"
	@echo "... modules/module_energy_sfc.o"
	@echo "... modules/module_energy_sfc.i"
	@echo "... modules/module_energy_sfc.s"
	@echo "... modules/module_finance_sfc.o"
	@echo "... modules/module_finance_sfc.i"
	@echo "... modules/module_finance_sfc.s"
	@echo "... modules/module_macro_sfc.o"
	@echo "... modules/module_macro_sfc.i"
	@echo "... modules/module_macro_sfc.s"
	@echo "... newmat10/bandmat.o"
	@echo "... newmat10/bandmat.i"
	@echo "... newmat10/bandmat.s"
	@echo "... newmat10/cholesky.o"
	@echo "... newmat10/cholesky.i"
	@echo "... newmat10/cholesky.s"
	@echo "... newmat10/evalue.o"
	@echo "... newmat10/evalue.i"
	@echo "... newmat10/evalue.s"
	@echo "... newmat10/fft.o"
	@echo "... newmat10/fft.i"
	@echo "... newmat10/fft.s"
	@echo "... newmat10/hholder.o"
	@echo "... newmat10/hholder.i"
	@echo "... newmat10/hholder.s"
	@echo "... newmat10/jacobi.o"
	@echo "... newmat10/jacobi.i"
	@echo "... newmat10/jacobi.s"
	@echo "... newmat10/myexcept.o"
	@echo "... newmat10/myexcept.i"
	@echo "... newmat10/myexcept.s"
	@echo "... newmat10/newfft.o"
	@echo "... newmat10/newfft.i"
	@echo "... newmat10/newfft.s"
	@echo "... newmat10/newmat1.o"
	@echo "... newmat10/newmat1.i"
	@echo "... newmat10/newmat1.s"
	@echo "... newmat10/newmat2.o"
	@echo "... newmat10/newmat2.i"
	@echo "... newmat10/newmat2.s"
	@echo "... newmat10/newmat3.o"
	@echo "... newmat10/newmat3.i"
	@echo "... newmat10/newmat3.s"
	@echo "... newmat10/newmat4.o"
	@echo "... newmat10/newmat4.i"
	@echo "... newmat10/newmat4.s"
	@echo "... newmat10/newmat5.o"
	@echo "... newmat10/newmat5.i"
	@echo "... newmat10/newmat5.s"
	@echo "... newmat10/newmat6.o"
	@echo "... newmat10/newmat6.i"
	@echo "... newmat10/newmat6.s"
	@echo "... newmat10/newmat7.o"
	@echo "... newmat10/newmat7.i"
	@echo "... newmat10/newmat7.s"
	@echo "... newmat10/newmat8.o"
	@echo "... newmat10/newmat8.i"
	@echo "... newmat10/newmat8.s"
	@echo "... newmat10/newmat9.o"
	@echo "... newmat10/newmat9.i"
	@echo "... newmat10/newmat9.s"
	@echo "... newmat10/newmatex.o"
	@echo "... newmat10/newmatex.i"
	@echo "... newmat10/newmatex.s"
	@echo "... newmat10/newmatnl.o"
	@echo "... newmat10/newmatnl.i"
	@echo "... newmat10/newmatnl.s"
	@echo "... newmat10/newmatrm.o"
	@echo "... newmat10/newmatrm.i"
	@echo "... newmat10/newmatrm.s"
	@echo "... newmat10/solution.o"
	@echo "... newmat10/solution.i"
	@echo "... newmat10/solution.s"
	@echo "... newmat10/sort.o"
	@echo "... newmat10/sort.i"
	@echo "... newmat10/sort.s"
	@echo "... newmat10/submat.o"
	@echo "... newmat10/submat.i"
	@echo "... newmat10/submat.s"
	@echo "... newmat10/svd.o"
	@echo "... newmat10/svd.i"
	@echo "... newmat10/svd.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

